export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  GAME_NOT_FOUND: "GAME_NOT_FOUND",
  TOURNAMENT_NOT_FOUND: "TOURNAMENT_NOT_FOUND",
  OPPONENT_NOT_FOUND: "OPPONENT_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DUPLICATE_JERSEY_NUMBER: "DUPLICATE_JERSEY_NUMBER",
  RATE_LIMITED: "RATE_LIMITED",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
